# Generated by Django 4.0.6 on 2022-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do Socio')),
                ('cpf', models.CharField(max_length=250, verbose_name='CPF do socio')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Valor em R$')),
                ('ano_pago', models.IntegerField(choices=[(1, '2019'), (2, '2022'), (3, '2023')], verbose_name='Ano pagto')),
                ('condicao_pago', models.IntegerField(choices=[(1, 'Em aberto'), (2, 'Pago'), (3, 'ate janeiro'), (4, 'ate fevereiro'), (5, 'ate março'), (6, 'ate abril'), (7, 'ate maio'), (8, 'ate junho'), (9, 'ate julho'), (10, 'ate agosto'), (11, 'ate setembro'), (12, 'ate outubro'), (13, 'ate novembro'), (14, 'ate dezembro')], verbose_name='Status pagto')),
                ('data_pago', models.DateField(verbose_name='Data pagamento')),
                ('observ', models.TextField(max_length=250, verbose_name='Observações')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('celular', models.CharField(max_length=250, verbose_name='Núm. celular')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Sócio cadastrado',
                'verbose_name_plural': 'Sócios cadastrados',
            },
        ),
    ]
