# Generated by Django 4.0.6 on 2023-07-28 13:11

import cpf_field.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='ano_pago',
            field=models.IntegerField(choices=[(1, '2021'), (2, '2022'), (3, '2023'), (4, '2024')], verbose_name='Ano pagto'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Núm. celular'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='condicao_pago',
            field=models.IntegerField(choices=[(1, 'Em aberto'), (2, 'Pago'), (3, 'Julho a dezembro'), (3, 'Ate janeiro'), (4, 'Ate fevereiro'), (5, 'Ate março'), (6, 'Ate abril'), (7, 'Ate maio'), (8, 'Ate junho'), (9, 'Ate julho'), (10, 'Ate agosto'), (11, 'Ate setembro'), (12, 'Ate outubro'), (13, 'Ate novembro'), (14, 'Ate dezembro')], verbose_name='Status pagto'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='CPF do socio'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='observ',
            field=models.TextField(blank=True, default='Mensalidades isentas 2020,2021 e 2022', max_length=150, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Valor em R$'),
        ),
    ]
