# Generated by Django 4.0.6 on 2023-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_cadastro_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Data Nascimento'),
        ),
    ]
