# Generated by Django 4.0.6 on 2023-07-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_cadastro_club_alter_cadastro_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='club',
        ),
    ]
